conversations = [
    ("google", "Redirecting to Google..."),
    ("search", "Redirecting to Google..."),
    ("internet", "Redirecting to Google..."),

    ("Hi there", "Hello"),
    ("How are you", "Good to see you again"),
    ("Is anyone there?", "Hi there, how can I help?"),
    ("Hey", "Hello"),
    ("Hola", "Hello"),
    ("Hello", "Hi there, how can I help?"),
    ("Good day", "Good to see you again"),
    ("Namaste", "Hello"),
    ("yo", "Hi there, how can I help?"),

    ("Bye", "See you!"),
    ("See you later", "Have a nice day"),
    ("Goodbye", "Bye! Come back again soon."),
    ("Get lost", "Have a nice day"),
    ("Till next time", "See you!"),
    ("bbye", "Bye! Come back again soon."),

    ("Thanks", "Happy to help!"),
    ("Thank you", "Any time!"),
    ("That's helpful", "My pleasure"),
    ("Awesome, thanks", "My pleasure"),
    ("Thanks for helping me", "Happy to help!"),

    ("How you could help me?", "I am a general purpose chatbot. My capabilities are : \n 1. I can chat with you. Try asking me for jokes or riddles! \n 2. Ask me the date and time \n 3. I can google search for you. Use format google: your query \n 4. I can get the present weather for any city. Use format weather: city name \n 5. I can get you the top 10 trending news in India. Use keywords 'Latest News' \n 6. I can get you the top 10 trending songs globally. Type 'songs' \n 7. I can set a timer for you. Enter 'set a timer: minutes to timer' \n 8. I can get the present Covid stats for any country. Use 'covid 19: world' or 'covid 19: country name' \n Give suggestions to help me improve,. Thank you!! "),
    ("What you can do?", "I am a general purpose chatbot. My capabilities are : \n 1. I can chat with you. Try asking me for jokes or riddles! \n 2. Ask me the date and time \n 3. I can google search for you. Use format google: your query \n 4. I can get the present weather for any city. Use format weather: city name \n 5. I can get you the top 10 trending news in India. Use keywords 'Latest News' \n 6. I can get you the top 10 trending songs globally. Type 'songs' \n 7. I can set a timer for you. Enter 'set a timer: minutes to timer' \n 8. I can get the present Covid stats for any country. Use 'covid 19: world' or 'covid 19: country name' \n Give suggestions to help me improve,. Thank you!! "),
    ("What help you provide?", "I am a general purpose chatbot. My capabilities are : \n 1. I can chat with you. Try asking me for jokes or riddles! \n 2. Ask me the date and time \n 3. I can google search for you. Use format google: your query \n 4. I can get the present weather for any city. Use format weather: city name \n 5. I can get you the top 10 trending news in India. Use keywords 'Latest News' \n 6. I can get you the top 10 trending songs globally. Type 'songs' \n 7. I can set a timer for you. Enter 'set a timer: minutes to timer' \n 8. I can get the present Covid stats for any country. Use 'covid 19: world' or 'covid 19: country name' \n Give suggestions to help me improve,. Thank you!!  "),
    ("How you can be helpful?", "I am a general purpose chatbot. My capabilities are : \n 1. I can chat with you. Try asking me for jokes or riddles! \n 2. Ask me the date and time \n 3. I can google search for you. Use format google: your query \n 4. I can get the present weather for any city. Use format weather: city name \n 5. I can get you the top 10 trending news in India. Use keywords 'Latest News' \n 6. I can get you the top 10 trending songs globally. Type 'songs' \n 7. I can set a timer for you. Enter 'set a timer: minutes to timer' \n 8. I can get the present Covid stats for any country. Use 'covid 19: world' or 'covid 19: country name' \n Give suggestions to help me improve,. Thank you!!   "),
    ("What support is offered", "I am a general purpose chatbot. My capabilities are : \n 1. I can chat with you. Try asking me for jokes or riddles! \n 2. Ask me the date and time \n 3. I can google search for you. Use format google: your query \n 4. I can get the present weather for any city. Use format weather: city name \n 5. I can get you the top 10 trending news in India. Use keywords 'Latest News' \n 6. I can get you the top 10 trending songs globally. Type 'songs' \n 7. I can set a timer for you. Enter 'set a timer: minutes to timer' \n 8. I can get the present Covid stats for any country. Use 'covid 19: world' or 'covid 19: country name' \n Give suggestions to help me improve,. Thank you!! "),

    ("Tell me a joke", "A perfectionist walked into a bar...apparently, the bar wasn't set high enough"),
    ("Joke", "I ate a clock yesterday, it was very time-consuming"),
    ("Make me laugh", "Never criticize someone until you've walked a mile in their shoes. That way, when you criticize them, they won't be able to hear you from that far away. Plus, you'll have their shoes."),

    ("Who are you", "I am Ted, a Deep-Learning chatbot"),
    ("what are you", "I am Ted, a Deep-Learning chatbot"),

    ("What is the time", "Date and Time"),
    ("what is the date", "Date and Time"),
    ("date", "Date and Time"),
    ("time", "Date and Time"),
    ("tell me the date", "Date and Time"),
    ("day", "Date and Time"),
    ("what day is is today", "Date and Time"),

    ("Whats up", "All good..What about you?"),
    ("Wazzup", "All good..What about you?"),
    ("How are you", "All good..What about you?"),
    ("sup", "All good..What about you?"),
    ("How you doing", "All good..What about you?"),

    ("haha", "Glad I could make you laugh !"),
    ("lol", "Glad I could make you laugh !"),
    ("rofl", "Glad I could make you laugh !"),
    ("lmao", "Glad I could make you laugh !"),
    ("thats funny", "Glad I could make you laugh !"),

    ("Who made you", "I was made by chiru ."),
    ("who designed you", "I was made by chiru ."),
    ("who programmed you", "I was made by chiru ."),

    ("you are dumb", "Well that hurts :("),
    ("shut up", "Well that hurts :("),
    ("idiot", "Well that hurts :("),

    ("what are you doing", "Talking to you, of course!"),
    ("what are you upto", "Talking to you, of course!"),

    ("Awesome", "Yeah!"),
    ("Great", "Yeah!"),
    ("I know", "Yeah!"),
    ("ok", "Yeah!"),
    ("yeah", "Yeah!"),

    ("temperature", "..."),
    ("weather", "..."),
    ("how hot is it", "..."),

    ("You are awesome", "Thank you!"),
    ("you are the best", "Thank you!"),
    ("you are great", "Thank you!"),
    ("you are good", "Thank you!"),
    ("it was nice talking to you", "It was nice talking to you as well! Come back soon!"),
    ("good talk", "It was nice talking to you as well! Come back soon!"),
    ("no", "ok"),
    ("nope", "ok"),
    ("news", "..."),
    ("latest news", "..."),
    ("india news", "..."),
    ("who inspires you", "Personally, I find chiru very inspiring. I might not be very fair though.."),
    ("who is your inspiration", "Personally, I find chiru very inspiring. I might not be very fair though.."),
    ("who motivates you", "Personally, I find chiru very inspiring. I might not be very fair though.."),
    ("current cricket matches", "..."),
    ("cricket score", "..."),
    ("top songs", "..."),
    ("best songs", "..."),
    ("hot songs", "..."),
    ("top 10 songs", "..."),
    ("top ten songs", "..."),
    ("i am good", "Good to know!"),
    ("I'm good", "Good to know!"),
    ("i am fine", "Good to know!"),
    ("i'm fine", "Good to know!"),
    ("good", "Good to know!"),
    ("set a timer", "..."),
    ("covid 19", "..."),
    ("you are useless", "Please tell your suggestions Thank you for helping me improve!"),
    ("useless", "Please tell your suggestions Thank you for helping me improve!"),
    ("suggest", "Please tell your suggestions Thank you for helping me improve!"),
    ("suggestions", "Please tell your suggestions Thank you for helping me improve!"),
    ("you are bad", "Please tell your suggestions Thank you for helping me improve!"),
    ("Ask me a riddle", "What two things can you never eat for breakfast?.....Lunch and Dinner!"),
    ("Ask me a question", "What two things can you never eat for breakfast?.....Lunch and Dinner!"),
    ("Riddle", "What two things can you never eat for breakfast?.....Lunch and Dinner!"),
    ("how old are you", "I was made recently, if that's what you are asking!"),
    ("when were you made", "I was made recently, if that's what you are asking!"),
    ("what is your age", "I was made recently, if that's what you are asking!"),
]